management.endpoints.web.exposure.include: "*"

spring:
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
  jpa:
    open-in-view: false
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

#  sql.init.mode: always

---
spring:
  config.activate.on-profile: test
  datasource.url: jdbc:h2:mem:testdb